<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="../bootstrap/css/style.css">
</head>
<h2>Sign In</h2>
<body class="container-fluid">

<!--Form containing input fields for registration-->
<form action="" method="post">
<div class="form-group">
    <label>Name</label>
    <input type="text" name="name" class="form-control" placeholder="Enter name">
    <br>
    <label for="email">Email</label>
    <input type="email" name="email" class="form-control" placeholder="Enter email address">
    <br>
    <label for="password">Password</label>
    <input type="password" name="pwd" class="form-control" placeholder="Enter password">
    <br>
    <label for="password">Re-Enter Password</label>
    <input type="password" name="confirmPwd" class="form-control" placeholder="Enter password">
    <br>
    <button type="submit" name="signInButton" class="btn btn-outline-dark">GET IN</button>
    <p><?php if(isset($view->error)) echo $view->error ?> </p>
</div>
</form>
</body>
<button id="regBack" name="regBack"><a href="index.php">Back to Home</a></button>
</html>
<?php require('template/footer.phtml'); ?>
